name: Increment Version

on:
  push:
    branches:
      - main

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '16'
      - name: Read version file
        id: read-version
        run: echo "$(cat version.txt)"
      - name: Increment version
        id: increment-version
        run: echo $(( $(cat version.txt) + 1 ))
      - name: Update version file
        run: echo "${{ steps.increment-version.outputs.stdout }}" > version.txt
      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git commit -am "Incremented version"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          directory: '.'
          force: true
