name: Increment Version Number

on:
  push:
    branches:
      - main

jobs:
  increment_version_number:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Increment version number
        run: |
          VERSION=$(cat version.txt)
          if [[ "$VERSION" =~ ^[0-9]+$ ]]; then
            NEW_VERSION=$((VERSION+1))
            echo $NEW_VERSION > version.txt
          else
            echo "Error: version.txt does not contain a valid version number"
            exit 1
          fi
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Increment version number'
          commit_options: '--no-verify'
