name: Create Release on Push

on:
  push:
    branches:
      - main

jobs:
  create_release:
    runs-on: ubuntu-latest
    env:
      MY_TOKEN: ${{ secrets.MY_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.3.0
        env:
          GITHUB_TOKEN: ${{ env.MY_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

      - name: Upload Asset
        uses: actions/upload-release-asset@v2.2.5
        env:
          GITHUB_TOKEN: ${{ env.MY_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .
          asset_name: repository-${{ github.sha }}.zip
          asset_content_type: application/zip
